name: rxcompute
description: "RxCompute â€” AI-Powered Pharmacy Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  bloc: ^9.0.0

  # HTTP & Networking
  dio: ^5.7.0
  web_socket_channel: ^3.0.1

  # Local Storage
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^9.2.4

  # Voice & Speech
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.0

  # UI & Fonts
  google_fonts: ^6.2.1

  # Charts
  fl_chart: ^0.69.2

  # Firebase & Auth
  firebase_core: ^3.8.1
  firebase_auth: ^5.4.1
  firebase_messaging: ^15.1.6
  google_sign_in: ^6.2.2
  audioplayers: ^6.1.0

  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.2.0+3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/sounds/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/app_icon.png"
  min_sdk_android: 21